name: ML Pipeline

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training script
        run: |
          python src/train_model.py  # Ensure the path is correct

      - name: Run tests
        run: |
          python src/test_model.py  # Ensure the path is correct

      - name: Install or Update AWS CLI
        run: |
          if command -v aws &> /dev/null; then
              echo "AWS CLI already installed. Updating..."
              sudo ./aws/install --update
          else
              echo "Installing AWS CLI..."
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install
          fi

      - name: Check AWS CLI version
        run: |
          aws --version

      - name: Deploy model to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1  # Change to your desired region
        run: |
          echo "Deploying model to S3..."
          aws s3 cp trained_model.joblib s3://your-bucket-name/path/to/model/